### ISSUE TITLE
build: complete tag integration with bower.io

### ISSUE THREAD

**Issue by mgenov** [clouway/clouwaypush#22]
A complete tag integration with bower.io:

http://bob.yexley.net/creating-and-maintaining-your-own-bower-package/

This need to be handled with tags: 0.1.0, 0.1.1, 0.1.2 and etc.

**Comment by mlesikov** [comment]
i will test  releasing versions via tag this :

 "dependencies": {
    "fontawesome": "latest"
  }

http://stackoverflow.com/questions/19030170/what-is-the-bower-version-syntax

**Comment by mlesikov** [comment]
tested with 
```json
"version": "0.1",
  "devDependencies": {
   ..
    "clouwaypush": "https://github.com/mlesikov/clouwaypush.git#*"
  },
```

and it finds the latest tag but the `version` field makes it fail : 
```text
bower clouwaypush#*         not-cached https://github.com/mlesikov/clouwaypush.git#*
bower clouwaypush#*            resolve https://github.com/mlesikov/clouwaypush.git#*
bower clouwaypush#*           checkout 0.0.3
bower clouwaypush#*              error Invalid Version: 1.0

Stack trace:
TypeError: Invalid Version: 1.0
    at new SemVer (/usr/local/lib/node_modules/bower/node_modules/semver/semver.js:273:11)
    at compare (/usr/local/lib/node_modules/bower/node_modules/semver/semver.js:460:10)

```

after removing the version it works as expected - adding a new version with a higher verision makes it `bower install` to update it in the main project

```text
bower clouwaypush#*         not-cached https://github.com/mlesikov/clouwaypush.git#*
bower clouwaypush#*            resolve https://github.com/mlesikov/clouwaypush.git#*
bower clouwaypush#*           checkout 0.0.4
bower clouwaypush#*           resolved https://github.com/mlesikov/clouwaypush.git#0.0.4
bower clouwaypush#*            install clouwaypush#0.0.4

clouwaypush#0.0.4 vendor/clouwaypush
└── angular#1.4.8

```

something that may become a problem is that  `angular' dependency, if the verions are not equals it may fail and requires version resolution.

a solution could be moveing that dependency as a devDependency, actaully we know that this library uses Angular at all

**Comment by mlesikov** [comment]
as a conclusion of my test 

I found that we have to call `bower update` instead of `bower install` - because `bower install` updates the version only first time.

bower work and with branch in the github repository, so I suggest the dependency to be described like that : 

```json
"devDependencies": {
   ..
    "clouwaypush": "https://github.com/mlesikov/clouwaypush.git#master"
  }
``` 

so every time when we call bower update the vendor/clouway push will contains the latest version of the master (branch), so no need of tags, no need of version update in telcong/bower.json, just pushing the commit 


[information reference](http://stackoverflow.com/questions/16949173/how-to-install-latest-untagged-state-of-a-repo-using-bower)

**Comment by mgenov** [comment]
Using of master sounds good to me.

**Comment by mlesikov** [comment]
this is the best solution, because it does not required anything additional like tags and update of the configurations.

**Comment by mlesikov** [comment]
bu tthe strange that I found was the behaviour of the `bower install`, that updates only the first time the version(if I touch something in the bower.json ) - it updates, after that it stops to fetch the latest version, so the solution is  - `bower update`
