### ISSUE TITLE
pushApi: firebase integration

### ISSUE THREAD

**Issue by mgenov** [clouway/clouwaypush#39]
As ChannelAPI is going to be deprecated in near future, the API need to be integrated with Firebase which has better features and is having GAE integrations. 

Using real-time evens on app engine: 
https://cloud.google.com/solutions/using-firebase-real-time-events-app-engine

**Comment by StanislavaKaukova** [comment]
Realizing a push events with firebase:
![firebase](https://user-images.githubusercontent.com/8342103/31063824-47fa7ad2-a73f-11e7-902f-3e7257f6b1ba.png)
